API_KEY = ""
SECRET_KEY = ""
API_URL = ""
DB_FILE = ""

EMAIL_ADDRESS = ''
EMAIL_PASSWORD = ''
EMAIL_HOST = ''
EMAIL_PORT = 

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET= ''
TWITTER_BEARER_TOKEN = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''
TWITTER_USERNAMES = [
    
]
